baseurl: ""
destination: "./_site/"

title: "Chris Brand"
description: "My name is Chris Brand (aka. Arcturial); I am a software developer, gamer and aspiring game designer from South Africa."

markdown: kramdown

sass:
    style: :compressed