paginate: 5
paginate_path: "page:num"
exclude: [ "README.md" ]
highlighter: pygments
markdown: kramdown

title: Chris Brand
author: Chris Brand
tagline: "Software Developer / Creator"
url: http://www.chrisbrand.co.za
description: "My name is Chris Brand (aka. Arcturial); I am a software developer, gamer and aspiring game designer from South Africa."

linkedin: https://za.linkedin.com/in/arcturial
github: https://arcturial.github.com/
twitter: https://twitter.com/Arcturial