title:          "Your awesome title"
email:          "your-email@domain.com"
description:    ""
baseurl:        ""
url:            "http://yourdomain.com"
markdown:       kramdown
source:         ./src/
destination:    ./public/